version: '3.3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: domo_api
    restart: unless-stopped
    volumes:
      - ./api:/var/www:cached
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: domo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "domo", "-U", "admin"]
      timeout: 5s
      retries: 5
    ports:
      - "7070:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: domo_front
    restart: unless-stopped
    ports:
      - "7171:80"

volumes:
  database_data:
