version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: domo_api
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - .:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: domo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: [DB_NAME]
      POSTGRES_PASSWORD: [PASSWORD]
      POSTGRES_USER: [USER]
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "domo", "-U", "admin"]
      timeout: 5s
      retries: 5
    ports:
      - "[DB_PORT]:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
